name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  read_msrv:
    name: Read MSRV
    uses: actions-rust-lang/msrv/.github/workflows/msrv.yml@8b553824444060021f2843d7b4d803f3624d15e5 # v0.1.0

  test:
    needs: read_msrv

    strategy:
      fail-fast: false
      matrix:
        version:
          - { name: msrv, version: "${{ needs.read_msrv.outputs.msrv }}" }
          - { name: stable, version: stable }
          - { name: nightly, version: nightly }

    name: tests / ${{ matrix.version.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install Rust (${{ matrix.version.name }})
        uses: actions-rust-lang/setup-rust-toolchain@f3c84ee10bf5a86e7a5d607d487bf17d57670965 # v1.5.0
        with:
          toolchain: ${{ matrix.version.version }}

      - name: Setup MySQL
        uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248 # v1.1
        with:
          mysql user: "ci"
          mysql password: "ci"

      - name: downgrades for MSRV
        if: matrix.version.name == 'msrv'
        run: |
          cargo update -p=idna_adapter --precise=1.2.0 # next ver: 1.82.0

      - run: cargo test
        env:
          DATABASE_URL: mysql://ci:ci@127.0.0.1:3306
